AllCops:
  RunRailsCops: true
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 250

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
